/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1;

import com.microsoft.rest.ServiceCall;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceException;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;

/**
 * An instance of this class provides access to all the operations defined
 * in GatewaysOperations.
 */
public interface GatewaysOperations {
    /**
     * Updates the credentials for the specified datasource.
     *
     * @param collectionName The workspace collection name
     * @param workspaceId The workspace id
     * @param gatewayId The gateway id
     * @param datasourceId The datasource id
     * @param datasourceDelta The datasource changes
     * @throws ServiceException exception thrown from REST call
     * @throws IOException exception thrown from serialization/deserialization
     * @throws IllegalArgumentException exception thrown from invalid parameters
     * @return the Object object wrapped in {@link ServiceResponse} if successful.
     */
    ServiceResponse<Object> patchDatasource(String collectionName, String workspaceId, String gatewayId, String datasourceId, Object datasourceDelta) throws ServiceException, IOException, IllegalArgumentException;

    /**
     * Updates the credentials for the specified datasource.
     *
     * @param collectionName The workspace collection name
     * @param workspaceId The workspace id
     * @param gatewayId The gateway id
     * @param datasourceId The datasource id
     * @param datasourceDelta The datasource changes
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if callback is null
     * @return the {@link ServiceCall} object
     */
    ServiceCall patchDatasourceAsync(String collectionName, String workspaceId, String gatewayId, String datasourceId, Object datasourceDelta, final ServiceCallback<Object> serviceCallback) throws IllegalArgumentException;

}
