// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the classes for PowerBIClient.
 */
package microsoft.powerbi.api.v1;
