/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1;

import java.util.List;
import okhttp3.Interceptor;
import okhttp3.logging.HttpLoggingInterceptor.Level;
import com.microsoft.rest.AutoRestBaseUrl;
import com.microsoft.rest.serializer.JacksonMapperAdapter;
import com.microsoft.rest.credentials.ServiceClientCredentials;

/**
 * The interface for PowerBIClient class.
 */
public interface PowerBIClient {
    /**
     * Gets the URL used as the base for all cloud service requests.
     *
     * @return the BaseUrl object.
     */
    AutoRestBaseUrl getBaseUrl();

    /**
     * Gets the list of interceptors the OkHttp client will execute.
     *
     * @return the list of interceptors.
     */
    List<Interceptor> getClientInterceptors();

    /**
     * Sets the logging level for OkHttp client.
     *
     * @param logLevel the logging level enum.
     */
    void setLogLevel(Level logLevel);

    /**
     * Gets the adapter for {@link com.fasterxml.jackson.databind.ObjectMapper} for serialization
     * and deserialization operations..
     *
     * @return the adapter.
     */
    JacksonMapperAdapter getMapperAdapter();

    /**
     * Gets Subscription credentials which uniquely identify client subscription..
     *
     * @return the credentials value.
     */
    ServiceClientCredentials getCredentials();

    /**
     * Sets Subscription credentials which uniquely identify client subscription..
     *
     * @param credentials the credentials value.
     */
    void setCredentials(ServiceClientCredentials credentials);

    /**
     * Gets the DatasetsOperations object to access its operations.
     * @return the DatasetsOperations object.
     */
    DatasetsOperations getDatasetsOperations();

    /**
     * Gets the GatewaysOperations object to access its operations.
     * @return the GatewaysOperations object.
     */
    GatewaysOperations getGatewaysOperations();

    /**
     * Gets the ImportsOperations object to access its operations.
     * @return the ImportsOperations object.
     */
    ImportsOperations getImportsOperations();

    /**
     * Gets the WorkspacesOperations object to access its operations.
     * @return the WorkspacesOperations object.
     */
    WorkspacesOperations getWorkspacesOperations();

    /**
     * Gets the ReportsOperations object to access its operations.
     * @return the ReportsOperations object.
     */
    ReportsOperations getReportsOperations();

}
