/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1;

import com.microsoft.rest.ServiceCall;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceException;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;
import microsoft.powerbi.api.v1.models.ODataResponseListReport;

/**
 * An instance of this class provides access to all the operations defined
 * in ReportsOperations.
 */
public interface ReportsOperations {
    /**
     * Gets a list of reports available within the specified workspace.
     *
     * @param collectionName The workspace collection name
     * @param workspaceId The workspace id
     * @throws ServiceException exception thrown from REST call
     * @throws IOException exception thrown from serialization/deserialization
     * @throws IllegalArgumentException exception thrown from invalid parameters
     * @return the ODataResponseListReport object wrapped in {@link ServiceResponse} if successful.
     */
    ServiceResponse<ODataResponseListReport> getReports(String collectionName, String workspaceId) throws ServiceException, IOException, IllegalArgumentException;

    /**
     * Gets a list of reports available within the specified workspace.
     *
     * @param collectionName The workspace collection name
     * @param workspaceId The workspace id
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if callback is null
     * @return the {@link ServiceCall} object
     */
    ServiceCall getReportsAsync(String collectionName, String workspaceId, final ServiceCallback<ODataResponseListReport> serviceCallback) throws IllegalArgumentException;

}
