/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;


/**
 * Object representing basic authentication credentials.
 */
public class BasicCredentials {
    /**
     * Username required to access the datasource.
     */
    private String username;

    /**
     * Password required to access the datasource.
     */
    private String password;

    /**
     * Get the username value.
     *
     * @return the username value
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Set the username value.
     *
     * @param username the username value to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get the password value.
     *
     * @return the password value
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Set the password value.
     *
     * @param password the password value to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

}
