/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A Power BI Column.
 */
public class Column {
    /**
     * The column name.
     */
    @JsonProperty(required = true)
    private String name;

    /**
     * The column data type.
     */
    @JsonProperty(required = true)
    private String dataType;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the dataType value.
     *
     * @return the dataType value
     */
    public String getDataType() {
        return this.dataType;
    }

    /**
     * Set the dataType value.
     *
     * @param dataType the dataType value to set
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

}
