/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;


/**
 * A Power BI datasource.
 */
public class Datasource {
    /**
     * The datasource name.
     */
    private String name;

    /**
     * The datasource connection string.
     */
    private String connectionString;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the connectionString value.
     *
     * @return the connectionString value
     */
    public String getConnectionString() {
        return this.connectionString;
    }

    /**
     * Set the connectionString value.
     *
     * @param connectionString the connectionString value to set
     */
    public void setConnectionString(String connectionString) {
        this.connectionString = connectionString;
    }

}
