/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;


/**
 * A Power BI gateway datasource.
 */
public class GatewayDatasource {
    /**
     * The unique id for this gateway datasource.
     */
    private String id;

    /**
     * The associated gateway id.
     */
    private String gatewayId;

    /**
     * The datasource type.
     */
    private String datasourceType;

    /**
     * The datasource connection details.
     */
    private String connectionDetails;

    /**
     * The datasource credential type.
     */
    private String credentialType;

    /**
     * The basicCredentials property.
     */
    private BasicCredentials basicCredentials;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Get the gatewayId value.
     *
     * @return the gatewayId value
     */
    public String getGatewayId() {
        return this.gatewayId;
    }

    /**
     * Set the gatewayId value.
     *
     * @param gatewayId the gatewayId value to set
     */
    public void setGatewayId(String gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * Get the datasourceType value.
     *
     * @return the datasourceType value
     */
    public String getDatasourceType() {
        return this.datasourceType;
    }

    /**
     * Set the datasourceType value.
     *
     * @param datasourceType the datasourceType value to set
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType;
    }

    /**
     * Get the connectionDetails value.
     *
     * @return the connectionDetails value
     */
    public String getConnectionDetails() {
        return this.connectionDetails;
    }

    /**
     * Set the connectionDetails value.
     *
     * @param connectionDetails the connectionDetails value to set
     */
    public void setConnectionDetails(String connectionDetails) {
        this.connectionDetails = connectionDetails;
    }

    /**
     * Get the credentialType value.
     *
     * @return the credentialType value
     */
    public String getCredentialType() {
        return this.credentialType;
    }

    /**
     * Set the credentialType value.
     *
     * @param credentialType the credentialType value to set
     */
    public void setCredentialType(String credentialType) {
        this.credentialType = credentialType;
    }

    /**
     * Get the basicCredentials value.
     *
     * @return the basicCredentials value
     */
    public BasicCredentials getBasicCredentials() {
        return this.basicCredentials;
    }

    /**
     * Set the basicCredentials value.
     *
     * @param basicCredentials the basicCredentials value to set
     */
    public void setBasicCredentials(BasicCredentials basicCredentials) {
        this.basicCredentials = basicCredentials;
    }

}
