/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;


/**
 * The import info.
 */
public class ImportInfo {
    /**
     * The file path to import.
     */
    private String filePath;

    /**
     * The import connection type.
     */
    private String connectionType;

    /**
     * Get the filePath value.
     *
     * @return the filePath value
     */
    public String getFilePath() {
        return this.filePath;
    }

    /**
     * Set the filePath value.
     *
     * @param filePath the filePath value to set
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * Get the connectionType value.
     *
     * @return the connectionType value
     */
    public String getConnectionType() {
        return this.connectionType;
    }

    /**
     * Set the connectionType value.
     *
     * @param connectionType the connectionType value to set
     */
    public void setConnectionType(String connectionType) {
        this.connectionType = connectionType;
    }

}
