/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;


/**
 * A Power BI Report.
 */
public class Report {
    /**
     * The report id.
     */
    private String id;

    /**
     * The report name.
     */
    private String name;

    /**
     * The report web url.
     */
    private String webUrl;

    /**
     * The report embed url.
     */
    private String embedUrl;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the webUrl value.
     *
     * @return the webUrl value
     */
    public String getWebUrl() {
        return this.webUrl;
    }

    /**
     * Set the webUrl value.
     *
     * @param webUrl the webUrl value to set
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }

    /**
     * Get the embedUrl value.
     *
     * @return the embedUrl value
     */
    public String getEmbedUrl() {
        return this.embedUrl;
    }

    /**
     * Set the embedUrl value.
     *
     * @param embedUrl the embedUrl value to set
     */
    public void setEmbedUrl(String embedUrl) {
        this.embedUrl = embedUrl;
    }

}
