/**
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.powerbi.api.v1.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A dataset table.
 */
public class Table {
    /**
     * The table name.
     */
    @JsonProperty(required = true)
    private String name;

    /**
     * The column schema for this table.
     */
    @JsonProperty(required = true)
    private List<Column> columns;

    /**
     * The data rows within this tabe.
     */
    private List<Row> rows;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the columns value.
     *
     * @return the columns value
     */
    public List<Column> getColumns() {
        return this.columns;
    }

    /**
     * Set the columns value.
     *
     * @param columns the columns value to set
     */
    public void setColumns(List<Column> columns) {
        this.columns = columns;
    }

    /**
     * Get the rows value.
     *
     * @return the rows value
     */
    public List<Row> getRows() {
        return this.rows;
    }

    /**
     * Set the rows value.
     *
     * @param rows the rows value to set
     */
    public void setRows(List<Row> rows) {
        this.rows = rows;
    }

}
